package kr.co.greentech.dataloggerapp.util.objects

object PreferenceKey {

    const val FILE_NAME_KEEP = "KEY_FILE_NAME_KEEP"
    const val FILE_SAVE_STATUS = "KEY_FILE_SAVE_STATUS"

    const val MEASURE_GRAPH_TYPE = "KEY_MEASURE_GRAPH_TYPE"
    const val MEASURE_TEXT_CHART_LAYOUT = "KEY_MEASURE_TEXT_CHART_LAYOUT"
    const val GRAPH_BUFFER_SIZE = "KEY_GRAPH_BUFFER_SIZE"
    const val MEASURE_MODE = "KEY_MEASURE_MODE"
    const val GRAPH_CHANNEL_COUNT = "KEY_GRAPH_CHANNEL_COUNT"

    const val ZERO_POINT = "KEY_ZERO_POINT"
    const val SUM_SET = "KEY_SUM_SET"
    const val AVERAGE_SET = "KEY_AVERAGE_SET"
    const val ZERO_POINT_LIST = "KEY_ZERO_POINT_LIST"
    const val FILTER_LIST = "KEY_FILTER_LIST"

    const val CHANNEL_COUNT = "KEY_CHANNEL_COUNT"
    const val MEASURE_SPEED = "KEY_MEASURE_SPEED_Float"
    const val SELECTED_CHANNEL_TO_MEASURE = "KEY_SELECTED_CHANNEL_TO_MEASURE"
    const val GRAPH_GRID_TYPE = "KEY_GRAPH_GRID_TYPE"
    const val STEP_XY_Y_AXIS = "KEY_STEP_XY_Y_AXIS"
    const val GRAPH_LINE_TYPE = "KEY_GRAPH_LINE_TYPE"
    const val STEP_GRAPH_INTERVAL = "KEY_STEP_GRAPH_INTERVAL"
    const val VISIBLE_MEASURE_TIME_TEST = "KEY_VISIBLE_MEASURE_TIME_TEST"
}